Repository Step3-kakao-tech-campus/Team15_BE, pull requests merged in 2023-10, with the labels that each got.

#7 [BE-02] 개발환경 세팅
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/resources/application.properties
  src/test/java/com/kakao/borrowme/BorrowmeApplicationTests.java
Labels: build

#9 [Merge] main to weekly/4
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/resources/application.properties
  src/test/java/com/kakao/borrowme/BorrowmeApplicationTests.java
Labels: merge

#14 [BE-06] 깃허브 템플릿 수정
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#18 [BE-03] H2 Database 로 임시 변경
  build.gradle
  src/main/resources/application.properties
Labels: fix, build

#20 [BE-08] 엔티티 및 레포지토리 생성
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/java/com/kakao/borrowme/category/Category.java
  src/main/java/com/kakao/borrowme/category/CategoryJPARepository.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLog.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogJPARepository.java
  src/main/java/com/kakao/borrowme/company/Company.java
  src/main/java/com/kakao/borrowme/company/CompanyJPARepository.java
  src/main/java/com/kakao/borrowme/location/Location.java
  src/main/java/com/kakao/borrowme/location/LocationJPARepository.java
  src/main/java/com/kakao/borrowme/product/Product.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/image/ProductImage.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
  src/main/java/com/kakao/borrowme/rental/Rental.java
  src/main/java/com/kakao/borrowme/rental/RentalJPARepository.java
  src/main/java/com/kakao/borrowme/review/Review.java
  src/main/java/com/kakao/borrowme/review/ReviewJPARepository.java
  src/main/java/com/kakao/borrowme/university/University.java
  src/main/java/com/kakao/borrowme/university/UniversityJPARepository.java
  src/main/java/com/kakao/borrowme/user/User.java
  src/main/java/com/kakao/borrowme/user/UserJPARepository.java
Labels: feat

#5 전남대_15조_BorrowMe_4주차
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/resources/application.properties
  src/test/java/com/kakao/borrowme/BorrowmeApplicationTests.java
Labels: review, merge

#28 [BE-09] application 설정 파일 변경
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: docs, refactor

#29 [BE-07] README.md 파일 수정
  README.md
Labels: docs, refactor, merge

#33 [BE-12] Spring Security 세팅
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/java/com/kakao/borrowme/_core/security/CustomUserDetails.java
  src/main/java/com/kakao/borrowme/_core/security/CustomUserDetailsService.java
  src/main/java/com/kakao/borrowme/_core/security/SecurityConfig.java
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/user/User.java
  src/main/java/com/kakao/borrowme/user/UserJPARepository.java
  src/main/java/com/kakao/borrowme/user/UserRequest.java
  src/main/java/com/kakao/borrowme/user/UserRestController.java
Labels: fix, build

#32 전남대_15조_BorrowMe_5주차
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  build.gradle
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/java/com/kakao/borrowme/category/Category.java
  src/main/java/com/kakao/borrowme/category/CategoryJPARepository.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLog.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogJPARepository.java
  src/main/java/com/kakao/borrowme/company/Company.java
  src/main/java/com/kakao/borrowme/company/CompanyJPARepository.java
  src/main/java/com/kakao/borrowme/location/Location.java
  src/main/java/com/kakao/borrowme/location/LocationJPARepository.java
  src/main/java/com/kakao/borrowme/product/Product.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/image/ProductImage.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
  src/main/java/com/kakao/borrowme/rental/Rental.java
  src/main/java/com/kakao/borrowme/rental/RentalJPARepository.java
  src/main/java/com/kakao/borrowme/review/Review.java
  src/main/java/com/kakao/borrowme/review/ReviewJPARepository.java
  src/main/java/com/kakao/borrowme/university/University.java
  src/main/java/com/kakao/borrowme/university/UniversityJPARepository.java
  src/main/java/com/kakao/borrowme/user/User.java
  src/main/java/com/kakao/borrowme/user/UserJPARepository.java
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: review

#24 [BE-10] Payment 기능 구현
  src/main/java/com/kakao/borrowme/_core/utils/ApiUtils.java
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinRequest.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
Labels: feat

#42 [Merge] weekly/5 to weekly/6
  src/main/java/com/kakao/borrowme/_core/errors/Exception404.java
  src/main/java/com/kakao/borrowme/_core/utils/ApiUtils.java
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinRequest.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductResponse.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: fix, merge

#34 [BE-13] Spring Security 세팅
  build.gradle
  src/main/java/com/kakao/borrowme/_core/security/JWTProvider.java
  src/main/java/com/kakao/borrowme/_core/security/JwtAuthenticationFilter.java
  src/main/java/com/kakao/borrowme/_core/security/SecurityConfig.java
Labels: fix, build

#43 [FIX] productId String 타입에서 Long 으로 변환
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
Labels: fix, merge

#45 [BE-14] 에러 코드 컨벤션 설정
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception400.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception401.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception403.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception404.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception409.java
  src/main/java/com/kakao/borrowme/_core/utils/ApiUtils.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
Labels: feat

#47 [Refactor] TODO 및 early return 적용
  src/main/java/com/kakao/borrowme/coin/CoinService.java
Labels: refactor

#53 [Merge] weekly/6 to develop
  build.gradle
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception400.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception401.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception403.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception404.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception409.java
  src/main/java/com/kakao/borrowme/_core/security/CustomUserDetails.java
  src/main/java/com/kakao/borrowme/_core/security/CustomUserDetailsService.java
  src/main/java/com/kakao/borrowme/_core/security/JWTProvider.java
  src/main/java/com/kakao/borrowme/_core/security/JwtAuthenticationFilter.java
  src/main/java/com/kakao/borrowme/_core/security/SecurityConfig.java
  src/main/java/com/kakao/borrowme/_core/utils/ApiUtils.java
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinRequest.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductResponse.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
  src/main/java/com/kakao/borrowme/user/User.java
  src/main/java/com/kakao/borrowme/user/UserJPARepository.java
  src/main/java/com/kakao/borrowme/user/UserRequest.java
  src/main/java/com/kakao/borrowme/user/UserRestController.java
Labels: merge

#54 [Merge] develop to main
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception400.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception401.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception403.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception404.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception409.java
  src/main/java/com/kakao/borrowme/_core/utils/ApiUtils.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductResponse.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: merge

#52 전남대_15조_BorrowMe_6주차
  build.gradle
  src/main/java/com/kakao/borrowme/BorrowmeApplication.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception400.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception401.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception403.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception404.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/Exception409.java
  src/main/java/com/kakao/borrowme/_core/security/CustomUserDetails.java
  src/main/java/com/kakao/borrowme/_core/security/CustomUserDetailsService.java
  src/main/java/com/kakao/borrowme/_core/security/JWTProvider.java
  src/main/java/com/kakao/borrowme/_core/security/JwtAuthenticationFilter.java
  src/main/java/com/kakao/borrowme/_core/security/SecurityConfig.java
  src/main/java/com/kakao/borrowme/_core/utils/ApiUtils.java
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinRequest.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductResponse.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
  src/main/java/com/kakao/borrowme/user/User.java
  src/main/java/com/kakao/borrowme/user/UserJPARepository.java
  src/main/java/com/kakao/borrowme/user/UserRequest.java
  src/main/java/com/kakao/borrowme/user/UserRestController.java
Labels: review, merge

#57 [BE-20] Coin Log 기능 구현
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogController.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogJPARepository.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/location/Location.java
  src/main/java/com/kakao/borrowme/product/Product.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/image/ProductImage.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: feat

#58 [BE-21] product 검색 기능 구현
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
Labels: feat

#59 [Merge] weekly/6 to weekly/7
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogController.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogJPARepository.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/location/Location.java
  src/main/java/com/kakao/borrowme/product/Product.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImage.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: fix, merge

#60 [Merge] weekly/7 to develop
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogController.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogJPARepository.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/location/Location.java
  src/main/java/com/kakao/borrowme/product/Product.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImage.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: merge

#61 [Merge] develop to main
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogController.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogJPARepository.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/location/Location.java
  src/main/java/com/kakao/borrowme/product/Product.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImage.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: merge

#62 전남대_15조_BorrowMe_7주차
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/Coin.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogController.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogJPARepository.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/location/Location.java
  src/main/java/com/kakao/borrowme/product/Product.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImage.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: review, merge

#64 [BE-23] 예외 처리 수정 및 피드백 반영
  src/main/java/com/kakao/borrowme/_core/errors/exception/InsufficientCoinException.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
Labels: refactor
