Repository Step3-kakao-tech-campus/Team15_BE, pull requests merged in 2023-11, with the labels that each got.

#74 [BE-15] 회원가입 & 로그인 기능 구현
  src/main/java/com/kakao/borrowme/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/kakao/borrowme/_core/errors/GlobalValidationHandler.java
  src/main/java/com/kakao/borrowme/_core/security/JWTProvider.java
  src/main/java/com/kakao/borrowme/_core/security/JwtAuthenticationFilter.java
  src/main/java/com/kakao/borrowme/university/UniversityJPARepository.java
  src/main/java/com/kakao/borrowme/user/User.java
  src/main/java/com/kakao/borrowme/user/UserRequest.java
  src/main/java/com/kakao/borrowme/user/UserRestController.java
  src/main/java/com/kakao/borrowme/user/UserService.java
  src/main/resources/application-local.yml
Labels: feat, fix, build

#82 전남대_15조_BorrowMe_9주차
  README.md
  src/main/java/com/kakao/borrowme/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/kakao/borrowme/_core/errors/GlobalValidationHandler.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/InsufficientCoinException.java
  src/main/java/com/kakao/borrowme/_core/security/JWTProvider.java
  src/main/java/com/kakao/borrowme/_core/security/JwtAuthenticationFilter.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/university/UniversityJPARepository.java
  src/main/java/com/kakao/borrowme/user/User.java
  src/main/java/com/kakao/borrowme/user/UserRequest.java
  src/main/java/com/kakao/borrowme/user/UserRestController.java
  src/main/java/com/kakao/borrowme/user/UserService.java
  src/main/resources/application-local.yml
Labels: review, merge

#84 [BE-25] 카카오 크램폴린 배포
  Dockerfile
  build.gradle
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/frontend.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  k8s/nginx.yaml
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/resources/application-ide.yml
Labels: feat, docs, build

#79 [BE-31] GlobalExceptionHandler 설계
  src/main/java/com/kakao/borrowme/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/InsufficientCoinException.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
Labels: refactor

#77 [BE-27] Rental 도메인 기능 구현
  src/main/java/com/kakao/borrowme/rental/Rental.java
  src/main/java/com/kakao/borrowme/rental/RentalResponse.java
  src/main/java/com/kakao/borrowme/rental/RentalRestController.java
  src/main/java/com/kakao/borrowme/rental/RentalService.java
Labels: feat, refactor

#80 [BE-28] Review 도메인 기능 구현
  src/main/java/com/kakao/borrowme/review/Review.java
  src/main/java/com/kakao/borrowme/review/ReviewController.java
  src/main/java/com/kakao/borrowme/review/ReviewJPARepository.java
  src/main/java/com/kakao/borrowme/review/ReviewRequest.java
  src/main/java/com/kakao/borrowme/review/ReviewResponse.java
  src/main/java/com/kakao/borrowme/review/ReviewService.java
Labels: feat

#71 [BE-29] 대여하기 기능 구현
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRequest.java
  src/main/java/com/kakao/borrowme/product/ProductResponse.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
Labels: feat, refactor

#85 [Merge] weekly/10 to develop
  Dockerfile
  README.md
  build.gradle
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/frontend.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  k8s/nginx.yaml
  src/main/java/com/kakao/borrowme/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/InsufficientCoinException.java
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRequest.java
  src/main/java/com/kakao/borrowme/product/ProductResponse.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
  src/main/java/com/kakao/borrowme/rental/Rental.java
  src/main/java/com/kakao/borrowme/rental/RentalResponse.java
  src/main/java/com/kakao/borrowme/rental/RentalRestController.java
  src/main/java/com/kakao/borrowme/rental/RentalService.java
  src/main/java/com/kakao/borrowme/review/Review.java
  src/main/java/com/kakao/borrowme/review/ReviewController.java
  src/main/java/com/kakao/borrowme/review/ReviewJPARepository.java
  src/main/java/com/kakao/borrowme/review/ReviewRequest.java
  src/main/java/com/kakao/borrowme/review/ReviewResponse.java
  src/main/java/com/kakao/borrowme/review/ReviewService.java
  src/main/resources/application-ide.yml
Labels: merge

#86 [Merge] develop to main
  Dockerfile
  build.gradle
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/frontend.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  k8s/nginx.yaml
  src/main/java/com/kakao/borrowme/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/kakao/borrowme/_core/errors/exception/InsufficientCoinException.java
  src/main/java/com/kakao/borrowme/_core/utils/DBInit.java
  src/main/java/com/kakao/borrowme/category/CategoryController.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/category/CategoryService.java
  src/main/java/com/kakao/borrowme/coin/CoinController.java
  src/main/java/com/kakao/borrowme/coin/CoinJPARepository.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
  src/main/java/com/kakao/borrowme/product/ProductJPARepository.java
  src/main/java/com/kakao/borrowme/product/ProductRequest.java
  src/main/java/com/kakao/borrowme/product/ProductResponse.java
  src/main/java/com/kakao/borrowme/product/ProductRestController.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/product/image/ProductImageJPARepository.java
  src/main/java/com/kakao/borrowme/rental/Rental.java
  src/main/java/com/kakao/borrowme/rental/RentalResponse.java
  src/main/java/com/kakao/borrowme/rental/RentalRestController.java
  src/main/java/com/kakao/borrowme/rental/RentalService.java
  src/main/java/com/kakao/borrowme/review/Review.java
  src/main/java/com/kakao/borrowme/review/ReviewController.java
  src/main/java/com/kakao/borrowme/review/ReviewJPARepository.java
  src/main/java/com/kakao/borrowme/review/ReviewRequest.java
  src/main/java/com/kakao/borrowme/review/ReviewResponse.java
  src/main/java/com/kakao/borrowme/review/ReviewService.java
  src/main/resources/application-ide.yml
Labels: merge

#88 [BE-00] GlobalValidationHandler 작성 및 수정
  src/main/java/com/kakao/borrowme/_core/errors/GlobalValidationHandler.java
  src/main/java/com/kakao/borrowme/category/CategoryResponse.java
  src/main/java/com/kakao/borrowme/coin/CoinService.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogResponse.java
  src/main/java/com/kakao/borrowme/coin/log/CoinLogService.java
Labels: feat, refactor

#89 [BE-00] product, rental, review 리펙토링
  src/main/java/com/kakao/borrowme/product/ProductRequest.java
  src/main/java/com/kakao/borrowme/product/ProductService.java
  src/main/java/com/kakao/borrowme/rental/RentalResponse.java
  src/main/java/com/kakao/borrowme/rental/RentalService.java
  src/main/java/com/kakao/borrowme/review/ReviewService.java
Labels: refactor

#92 [Merge] weekly/10 to develop
  k8s/backend.yaml
Labels: merge

#93 [Merge] develop to main
  k8s/backend.yaml
Labels: merge

#94 [BE-00] 백엔드 레포지토리 주소 변경
  k8s/backend.yaml
Labels: fix
